### ISSUE TITLE
We should only connect to Web3 on the Checkout page, not the main page

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#123]
Currently, we request to connect to Web3 on the main fundraising page. This is not ideal as users might want to browse the site, before being asked to connect to Web3

For the main page, we are already using Infura as a fallback to obtain data from nodes.

What we can do instead is to
- Have a "Connect to Web3" button on the Checkout page (use Blocknative? So not just Metamask, but Portis, Fortmatic as well)
- Show a field for the lender's address in the Checkout page once Web3 has loaded

For the main page, we can still access Web3 from Infura, although those might take some time to load.

**Comment by adibas03** [comment]
One problem, with this is the inconsistency of infura,
so, The browser Web3 is far preferred,
probably delay asking for accounts (`provider.enable`) till when about to contribute

**Comment by onggunhao** [comment]
We can also explore others (Alchemy, TheGraph)

**Comment by adibas03** [comment]
implemented a temp fix by only requesting access on the `invest Now`, `My Investment` and `Faucet` pages

**Comment by onggunhao** [comment]
Thanks @adibas03!
