### ISSUE TITLE
Cleanup Eslint for compiled without warnings.

### ISSUE THREAD

**Issue by urmauur** [enabledao/enable-ui#139]
<img width="1680" alt="Screen Shot 2019-10-10 at 15 17 51" src="https://user-images.githubusercontent.com/10354610/66551182-22d92a00-eb71-11e9-870a-5ed9c0e98b1d.png">

**Comment by urmauur** [comment]
@onggunhao https://github.com/enabledao/enable-ui/pull/140

**Comment by onggunhao** [comment]
Thank you so much @urmauur
