### ISSUE TITLE
Should have way of funding loan using Ether (instead of just Dai)

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#149]
Linked to issue #148

@litocoen has suggested that we provide an option to fund using Ether. 

## Issue
* Users may not have Dai balance, but want to give using Ether
* Difficult to obtain Dai (no Binance listing of Dai, etc)

## Possible solution
* Use Uniswap or Kyber pool to convert Ether to Dai (need to calculate the exact amount to charge in Ether
* What is the slippage associated with this method?
* Should we prioritize Portis (credit card) or Ether-to-Dai?

**Comment by adibas03** [comment]
**centralized exchange alternatives** (To cover all bases):
https://coinswitch.co

**Comment by tspoff** [comment]
**Two-step process**
Totally viable via uniswap as mentioned, still need to think about slippage

**Helper Contract to automate** 
The issue there is that the 'funder' address will be tracked the helper contract, as we track funder via msg.sender

**Comment by onggunhao** [comment]
@tspoff That makes sense, let's just focus on #153
