### ISSUE TITLE
Contributor list should be ordered from most recent to new

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#152]
![image](https://user-images.githubusercontent.com/518024/66714877-21b53080-edef-11e9-8c59-5cb442da3f22.png)

**Comment by JorgeAndd** [comment]
I will try working on this one

**Comment by adibas03** [comment]
@onggunhao The subtitle states `highest contributors till date`,
are we switching now to most recent contributions?

**Comment by onggunhao** [comment]
Ahh! That makes sense. Sorry. Let's close this issue and move on
