### ISSUE TITLE
Implement web3 calls from UI to enable-contracts

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#8]
We will need to make the Web3 calls (and show success / failure modals) and interact with the smart contracts

# 1. Authorizing Web3

![](https://raw.githubusercontent.com/enabledao/enable/master/product/specs/2019-07-14-v0.1-specs-(ines)/designs/1-request-permission.png)

# 2. Loan Page

![](https://raw.githubusercontent.com/enabledao/enable/master/product/specs/2019-07-14-v0.1-specs-(ines)/designs/2-loan-page.png)

# 3. Personal Details

![](https://raw.githubusercontent.com/enabledao/enable/master/product/specs/2019-07-14-v0.1-specs-(ines)/designs/3-personal-details.png)

# 4. Make Loan

![](https://raw.githubusercontent.com/enabledao/enable/master/product/specs/2019-07-14-v0.1-specs-(ines)/designs/4-make-loan.png)

# 5. My Loan

![](https://raw.githubusercontent.com/enabledao/enable/master/product/specs/2019-07-14-v0.1-specs-(ines)/designs/5-my-loan.png)

**Comment by onggunhao** [comment]
Previous discussion on Ethereum-based data reading https://github.com/enabledao/enable/issues/24

**Comment by adibas03** [comment]
To checkout https://github.com/blocknative/assist
