### ISSUE TITLE
Should replace `this.props.paymentToken ? :` with a check to see if web3 has loaded

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#80]
See simulationReturn.tsx

**Comment by adibas03** [comment]
@onggunhao 
I need more information on this.

**Comment by onggunhao** [comment]
@adibas03 Ah I actually already fixed it and should have closed the issue.

This was basically
1. We used to pull loan variables from the smart contract, and thus had a conditional checking for `this.props.paymentToken`
2. Now that we are pulling it from constants, we don't need this any more

Closing issue
