### ISSUE TITLE
Refactor `MyLoan` component to have sub-components (renderConnectWallet, renderLenderLoan, renderBorrowerLoan)

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#95]
Right now, the component is way too bloated. Let's move out the 3 sub-components into their own component and import them

**Comment by adibas03** [comment]
@djuanit0x how is progress on this?

**Comment by djuanit0x** [comment]
1/3. Sure! I will push the update after this.

**Comment by djuanit0x** [comment]
render-components #160
