### ISSUE TITLE
Fix Ines' "Credit Profile" so that overflow is hidden

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#96]
We should hide the overflowing address on this

![image](https://user-images.githubusercontent.com/518024/65821308-fac5fe80-e233-11e9-8105-c31c1437f3f4.png)

**Comment by urmauur** [comment]
hi @onggunhao i take this issue

**Comment by urmauur** [comment]
https://github.com/enabledao/enable-ui/pull/137
